# To built image:
# docker-compose build

# To start:
# docker-compose up

version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD@db:5432/postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=PASSWORD
      - SUMMARIZER_URL=http://summarizer:8001
    depends_on:
      - db
      - summarizer
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  summarizer:
    build:
      context: ./summarizer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - HF_TOKEN=hf_your_token_here
      - GOOGLE_API_KEY=AIzaSyBcizqje0iym5bPHx-OoepPbGqGcuLADKM
      - WHISPER_MODEL=normal
      - USE_GPU=true
      - MIN_DURATION=0.5
      - GAP_THRESHOLD=4.0
      - MAX_TOKENS_PER_CHUNK=800
      - MEETING_TYPE=generic meeting
      - FOCUS_REQUEST=Focus on tasks, decisions, deadlines.
    volumes:
      - ./summarizer/data:/app/data
      - ./summarizer/results:/app/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: